### PR TITLE
feat: Add poetry as dependency manager

### PR DESCRIPTION
**Pull request by acuriel**
Added poetry as dependency management. This will allow a more exact dependency versioning and project description in the repository itself. Also, it allows us to split off the dependencies into groups, ex. `general`, `dev`, and `test`., and control which one to install when.
Check [Poetry Docs](https://python-poetry.org/docs/basic-usage/) for more information about how to use it.
Also, the `requirements.txt` file was updated with the version constraints using the command:
`poetry export --with test --without-hashes --output .\requirements.txt`

Assumptions
For the PR, it was assumed that the version of Python used is 3.10, and for the dependencies, the last compatible version was used.

### CODE REVIEW

**Comment by albexl** [comment]
@acuriel it would be good to know how to use `poetry` to keep our dependencies updated. I'm new to `poetry` myself, and maybe some other contributors are also new to it. Maybe add the basic commands to run after a particular set of changes are made?

I'm reading the documentation, but I think having this kind of `cheat sheet` for us newbies can be useful. Do you agree?

**Comment by acuriel** [comment]
Yep, of course! Should i add it to the README?

**Comment by albexl** [comment]
> Yep, of course! Should i add it to the README?

I guess it would be good on the `README`. I don't know if there is any convention for documentation on Python repos. If there is, I think we should follow it. Maybe having a `docs` folder? I leave it to your consideration.

One thing to consider though:
- If we should run some `poetry` commands after making some changes, then this should also be told on the `CONTRIBUTING` file. Do you agree?

**Comment by ArielXL** [comment]
> I guess it would be good on the `README`. I don't know if there is any convention for documentation on Python repos. If there is, I think we should follow it. Maybe having a `docs` folder? I leave it to your consideration.
> 
> One thing to consider though:
> 
> * If we should run some `poetry` commands after making some changes, then this should also be told on the `CONTRIBUTING` file. Do you agree?

As a suggestion, you can make a makefile to run these commands for ease of use.

**Comment by albexl** [comment]
Hi, @acuriel are you still working on this? No rush, I just want to know a little bit of the status since I plan to add some new implementations soon and this poetry thing sounded really good.

**Comment by acuriel** [comment]
Hi @albexl , yep, i have it ready and set up, but i haven't  updated the readme 😅. Let me do it tomorrow and also to add some reference links and examples so everyone can make a smooth transition

**Comment by acuriel** [comment]
> commands

Hmm, I'm not sure if a makefile here would be worth it. We would need to document  the commands, and at the end, the poetry cli is really simple and well documented. Maybe a reference and examples could bw enough

**Comment by ArielXL** [comment]
> > commands
> 
> Hmm, I'm not sure if a makefile here would be worth it. We would need to document the commands, and at the end, the poetry cli is really simple and well documented. Maybe a reference and examples could bw enough

👍🏻👍🏻

**Pull request merged**
