### PR TITLE
fix: Remove TestCase in test base class

### PR DESCRIPTION
**Pull request by gabyarte**

### CODE REVIEW

**Review by albexl — COMMENTED** [review]
Can you explain how this allows us to add more test cases for a specific Test class? Maybe add an example or two?

**Comment by albexl** [comment]
I think what I had in mind was something like this [test_sorting](https://github.com/albexl/data-structures-for-teaching/blob/dev/tests/test_sorting.py). This way we can easily add test cases to try different sorting methods, union-find implementations, etc...

**Comment by gabyarte** [comment]
No, I think it doesn't allow it. My proposal only solved the issue that was happening before and the expansion to other tests using classes that will inherit from the mixin and the `TestCase` class and set the proper attributes (`union_find`, `heap`, etc.). I think in that case, I can close it

**Comment by albexl** [comment]
Ok. Let's close it. Still, I think my proposal for the sorting algorithms is not a perfect fit for union-find, stack, etc... so maybe I will have a more thorough look at this topic.

**Pull request closed without merging**
